### ISSUE TITLE
Список продуктов

### ISSUE THREAD

**Issue by xalvaine** [new-year-2022/.github#1]
### Для фруктовой ёлочки:
- [ ] Мандарины (много)
- [ ] Виноград белый 1 гроздь
- [ ] Виноград чёрный 1 гроздь
- [x] Яблоко большое 1 шт
- [ ] Клубника ~300 гр
- [x] Киви 3 шт
- [ ] Зубочистки 

### Для запекания курочки
- [x] Куриные ножки + филейка для нагггетсов
- [x] Чеснок 1 головка
- [x] Специи для запекания курицы @gabrieleger
- [x] Масло подсолнечное (если что у меня есть много) @gabrieleger
- [x] Перец болгарский
- [ ] сухарь для панировки @xalvaine 

### Для оливье
- [x] Морковка 3шт (одну длинную и прямую для ёлочки и 2 среднего размера)
- [x] Картошка (+для запекания картоха) всего 15 картошек среднего размера (брать фиолетоватый “Лаура” или спросить у продавцов какая не разваливается)
- [ ] Огурчик маринованный 
- [x] Горошек
- [ ] Майонез 250 гр
- [ ] Докторская колбаса/копчёная
- [x] Яйца 3шт

Прочее:
- [ ] Вино из икеи (?)
- [x] Бенгальские огоньки @straivi 
- [x] Компотик с персиком

**Comment by xalvaine** [comment]
- Чеснок 1 головка - 11р
- Горошек - 93р
- 3 яйца - 24р

**Comment by gabrieleger** [comment]
- персик консервированный - 140р
- яблоко большое - 22р
- куриные ножки - 278р 
- приправы - 40р
- киви - 42р
- грудка - 194р
- красный перец - 95р
- самое первое вино - 539р
- сыр - 140р
- фрукты в пятёрочке - 135р
---
всего: 1625р

**Comment by gabrieleger** [comment]
Матвею:
- 140 сыр
- 760 вторая бутылка вина
- 214 вольчек для матвея и тимофея
- 1200 перек

**Comment by xalvaine** [comment]
все
- какое-то мясо 239
- сыр 140

я и Эля
- вино 890
